version: '3'

services:
  rabbit:
    image: "rabbitmq:3-management"
    container_name: "nbRabbit"
    hostname: "rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  redis:
    image: redis
    container_name: "nbRedis"
    ports: 
      - "6379:6379"